gogs:
  image: "gogs/gogs:latest"
  net: "host"
  volumes:
    - ".docker/gogs:/data"
drone:
  image: "drone/drone:0.5"
  volumes:
    - ".docker/drone:/var/lib/drone"
  restart: always
  net: "host"
  environment:
    DRONE_OPEN: "true"
    DRONE_AGENT_SECRET: "drone"
    DRONE_GOGS: "true"
    DRONE_GOGS_URL: "http://localhost:3000"
    I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
    I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
